name: build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: npm
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: dist-bundle
        path: dist
        retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        repository: causti-co/causti-co.github.io
        ssh-key: '${{ secrets.DEPLOY_KEY }}'
    - uses: actions/download-artifact@v4
      with:
        name: dist-bundle
    - run: |
        git config --global user.name "${{github.event.commits[0].author.name}}"
        git config --global user.email "${{github.event.commits[0].author.email}}"
        git add .
        git commit -am "${{github.event.commits[0].message}}"
        git push